// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoShop.EFDataAcccess;

namespace VideoShop.EFDataAcccess.Migrations
{
    [DbContext(typeof(VideoShopContext))]
    [Migration("20200403003356_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoShop.Pocos.BorrowerPoco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BorrowerName")
                        .HasColumnName("Borrower_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnName("Date_of_Birth")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Borrower");
                });

            modelBuilder.Entity("VideoShop.Pocos.VideoPoco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Borrower_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnName("Release_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoName")
                        .HasColumnName("Video_Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Borrower_ID");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("VideoShop.Pocos.VideoPoco", b =>
                {
                    b.HasOne("VideoShop.Pocos.BorrowerPoco", "Borrower")
                        .WithMany("Videos")
                        .HasForeignKey("Borrower_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
